### ISSUE TITLE
Getting this error on Kali

### ISSUE THREAD

**Issue by jaykali** [RenwaX23/XSSTRON#20]
![xsstron error](https://user-images.githubusercontent.com/62602243/120096106-29058b00-c147-11eb-934b-22ec6c969d35.png)

Here is the log file
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
1 info using npm@7.5.2
2 info using node@v12.21.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/kali/XSSTRON/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 87a8f9968da7795b
20 timing npm:load Completed in 14ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree:init Completed in 91ms
23 timing idealTree:userRequests Completed in 0ms
24 silly idealTree buildDeps
25 silly fetch manifest electron@^10.0
26 http fetch GET 304 https://registry.npmjs.org/electron 1281ms (from cache)
27 silly placeDep ROOT electron@10.4.7 REPLACE for: XSSTRON@1.0.0 want: ^10.0
28 timing idealTree:#root Completed in 1295ms
29 timing idealTree:node_modules/electron Completed in 0ms
30 timing idealTree:buildDeps Completed in 1296ms
31 timing idealTree:fixDepFlags Completed in 2ms
32 timing idealTree Completed in 1391ms
33 timing reify:loadTrees Completed in 1391ms
34 timing reify:diffTrees Completed in 1ms
35 silly reify moves {}
36 timing reify:retireShallow Completed in 0ms
37 timing reify:createSparse Completed in 169ms
38 timing reify:loadBundles Completed in 0ms
39 timing reifyNode:node_modules/wrappy Completed in 297ms
40 timing reifyNode:node_modules/universalify Completed in 298ms
41 timing reifyNode:node_modules/url-parse-lax Completed in 298ms
42 timing reifyNode:node_modules/to-readable-stream Completed in 297ms
43 timing reifyNode:node_modules/process-nextick-args Completed in 298ms
44 timing reifyNode:node_modules/prepend-http Completed in 298ms
45 timing reifyNode:node_modules/once Completed in 298ms
46 timing reifyNode:node_modules/sumchecker/node_modules/ms Completed in 298ms
47 timing reifyNode:node_modules/npm-conf/node_modules/pify Completed in 298ms
48 timing reifyNode:node_modules/ms Completed in 298ms
49 timing reifyNode:node_modules/mimic-response Completed in 298ms
50 timing reifyNode:node_modules/lowercase-keys Completed in 298ms
51 timing reifyNode:node_modules/ini Completed in 298ms
52 timing reifyNode:node_modules/end-of-stream Completed in 298ms
53 timing reifyNode:node_modules/duplexer3 Completed in 298ms
54 timing reifyNode:node_modules/decompress-response Completed in 298ms
55 timing reifyNode:node_modules/buffer-from Completed in 298ms
56 timing reifyNode:node_modules/buffer-crc32 Completed in 298ms
57 timing reifyNode:node_modules/@electron/get/node_modules/ms Completed in 299ms
58 timing reifyNode:node_modules/lru-cache Completed in 302ms
59 timing reifyNode:node_modules/config-chain Completed in 302ms
60 timing reifyNode:node_modules/serialize-error Completed in 305ms
61 timing reifyNode:node_modules/pend Completed in 305ms
62 timing reifyNode:node_modules/p-cancelable Completed in 305ms
63 timing reifyNode:node_modules/normalize-url Completed in 305ms
64 timing reifyNode:node_modules/matcher Completed in 305ms
65 timing reifyNode:node_modules/inherits Completed in 305ms
66 timing reifyNode:node_modules/get-stream Completed in 304ms
67 timing reifyNode:node_modules/env-paths Completed in 305ms
68 timing reifyNode:node_modules/escape-string-regexp Completed in 305ms
69 timing reifyNode:node_modules/encodeurl Completed in 305ms
70 timing reifyNode:node_modules/detect-node Completed in 305ms
71 timing reifyNode:node_modules/cacheable-request/node_modules/lowercase-keys Completed in 305ms
72 timing reifyNode:node_modules/yallist Completed in 309ms
73 timing reifyNode:node_modules/responselike Completed in 309ms
74 timing reifyNode:node_modules/jsonfile Completed in 309ms
75 timing reifyNode:node_modules/http-cache-semantics Completed in 309ms
76 timing reifyNode:node_modules/clone-response Completed in 308ms
77 timing reifyNode:node_modules/@szmarczak/http-timer Completed in 308ms
78 timing reifyNode:node_modules/yauzl Completed in 312ms
79 timing reifyNode:node_modules/util-deprecate Completed in 312ms
80 timing reifyNode:node_modules/keyv Completed in 311ms
81 timing reifyNode:node_modules/concat-stream/node_modules/safe-buffer Completed in 310ms
82 timing reifyNode:node_modules/proto-list Completed in 314ms
83 timing reifyNode:node_modules/defer-to-connect Completed in 313ms
84 timing reifyNode:node_modules/cacheable-request/node_modules/get-stream Completed in 312ms
85 timing reifyNode:node_modules/pump Completed in 316ms
86 timing reifyNode:node_modules/graceful-fs Completed in 315ms
87 timing reifyNode:node_modules/extract-zip Completed in 315ms
88 timing reifyNode:node_modules/concat-stream/node_modules/string_decoder Completed in 314ms
89 timing reifyNode:node_modules/concat-stream Completed in 314ms
90 timing reifyNode:node_modules/mkdirp Completed in 318ms
91 timing reifyNode:node_modules/concat-stream/node_modules/isarray Completed in 318ms
92 timing reifyNode:node_modules/json-buffer Completed in 321ms
93 timing reifyNode:node_modules/core-util-is Completed in 321ms
94 timing reifyNode:node_modules/utf8-byte-length Completed in 325ms
95 timing reifyNode:node_modules/progress Completed in 324ms
96 timing reifyNode:node_modules/sumchecker/node_modules/debug Completed in 324ms
97 timing reifyNode:node_modules/cacheable-request Completed in 322ms
98 timing reifyNode:node_modules/@electron/get/node_modules/debug Completed in 323ms
99 timing reifyNode:node_modules/@sindresorhus/is Completed in 324ms
100 timing reifyNode:node_modules/semver-compare Completed in 329ms
101 timing reifyNode:node_modules/fd-slicer Completed in 328ms
102 timing reifyNode:node_modules/truncate-utf8-bytes Completed in 330ms
103 timing reifyNode:node_modules/json-stringify-safe Completed in 329ms
104 timing reifyNode:node_modules/es6-error Completed in 329ms
105 timing reifyNode:node_modules/sanitize-filename Completed in 331ms
106 timing reifyNode:node_modules/typedarray Completed in 335ms
107 timing reifyNode:node_modules/npm-conf Completed in 333ms
108 timing reifyNode:node_modules/global-tunnel-ng Completed in 333ms
109 timing reifyNode:node_modules/define-properties/node_modules/object-keys Completed in 334ms
110 timing reifyNode:node_modules/boolean Completed in 334ms
111 timing reifyNode:node_modules/define-properties Completed in 336ms
112 timing reifyNode:node_modules/sprintf-js Completed in 339ms
113 timing reifyNode:node_modules/tunnel Completed in 340ms
114 timing reifyNode:node_modules/debug Completed in 343ms
115 timing reifyNode:node_modules/sumchecker Completed in 349ms
116 timing reifyNode:node_modules/minimist Completed in 349ms
117 timing reifyNode:node_modules/got Completed in 350ms
118 timing reifyNode:node_modules/globalthis Completed in 351ms
119 timing reifyNode:node_modules/electron Completed in 353ms
120 timing reifyNode:node_modules/roarr Completed in 358ms
121 timing reifyNode:node_modules/type-fest Completed in 359ms
122 timing reifyNode:node_modules/concat-stream/node_modules/readable-stream Completed in 358ms
123 timing reifyNode:node_modules/global-agent/node_modules/semver Completed in 378ms
124 timing reifyNode:node_modules/fs-extra Completed in 381ms
125 timing reifyNode:node_modules/@electron/get Completed in 382ms
126 timing reifyNode:node_modules/@types/node Completed in 387ms
127 timing reifyNode:node_modules/global-agent Completed in 395ms
128 timing reifyNode:node_modules/lodash Completed in 618ms
129 timing reifyNode:node_modules/core-js Completed in 701ms
130 timing reify:unpack Completed in 704ms
131 timing reify:unretire Completed in 0ms
132 timing build:queue Completed in 7ms
133 timing build:link:node_modules/electron Completed in 2ms
134 timing build:link:node_modules/extract-zip Completed in 2ms
135 timing build:link:node_modules/global-agent/node_modules/semver Completed in 2ms
136 timing build:link:node_modules/mkdirp Completed in 2ms
137 timing build:link Completed in 3ms
138 info run core-js@3.8.2 postinstall node_modules/core-js node -e "try{require('./postinstall')}catch(e){}"
139 info run electron@10.4.7 postinstall node_modules/electron node install.js
140 info run core-js@3.8.2 postinstall { code: 0, signal: null }
141 timing build:run:postinstall:node_modules/core-js Completed in 79ms
142 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 1251ms
143 timing auditReport:getReport Completed in 1253ms
144 timing metavuln:cache:get:security-advisory:lodash:QECQhqENwQoNVl6da4JbJcLbJD29giB5sLJN+gaFqW+TzG4UNvuVAr/wBc9mvIFVshry+iHa5VIaBdTVItbLtg== Completed in 16ms
145 http fetch GET 304 https://registry.npmjs.org/lodash 247ms (from cache)
146 timing metavuln:packument:lodash Completed in 250ms
147 timing metavuln:load:security-advisory:lodash:1673 Completed in 3ms
148 timing metavuln:calculate:security-advisory:lodash:1673 Completed in 257ms
149 timing metavuln:cache:get:security-advisory:global-tunnel-ng:D5CWMYQ/e62QpYXbX+2XNNLwIlZsYz6VBwLOpR49Ymfbu0dv4pBQ5G/lukeeypPU0l5wwzFB4uRs4fQHLAt/Vw== Completed in 5ms
150 http fetch GET 304 https://registry.npmjs.org/global-tunnel-ng 273ms (from cache)
151 timing metavuln:packument:global-tunnel-ng Completed in 276ms
152 timing metavuln:load:security-advisory:global-tunnel-ng:QECQhqENwQoNVl6da4JbJcLbJD29giB5sLJN+gaFqW+TzG4UNvuVAr/wBc9mvIFVshry+iHa5VIaBdTVItbLtg== Completed in 0ms
153 timing metavuln:calculate:security-advisory:global-tunnel-ng:QECQhqENwQoNVl6da4JbJcLbJD29giB5sLJN+gaFqW+TzG4UNvuVAr/wBc9mvIFVshry+iHa5VIaBdTVItbLtg== Completed in 277ms
154 timing auditReport:init Completed in 542ms
155 timing reify:audit Completed in 1797ms
156 info run electron@10.4.7 postinstall { code: 1, signal: null }
157 timing reify:rollback:createSparse Completed in 183ms
158 timing reify:rollback:retireShallow Completed in 0ms
159 timing command:install Completed in 336234ms
160 verbose stack Error: command failed
160 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
160 verbose stack     at ChildProcess.emit (events.js:314:20)
160 verbose stack     at maybeClose (internal/child_process.js:1022:16)
160 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
161 verbose pkgid electron@10.4.7
162 verbose cwd /home/kali/XSSTRON
163 verbose Linux 5.10.0-kali7-amd64
164 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
165 verbose node v12.21.0
166 verbose npm  v7.5.2
167 error code 1
168 error path /home/kali/XSSTRON/node_modules/electron
169 error command failed
170 error command sh -c node install.js
171 error Error: EACCES: permission denied, stat '/root/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv10.4.7SHASUMS256.txt/SHASUMS256.txt'
172 verbose exit 1
```

**Comment by RenwaX23** [comment]
sorry about that maybe try other platform
