### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by soufianetahiri** [RenwaX23/XSSTRON#8]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle XSSTRON@1.0.0~prestart: XSSTRON@1.0.0
6 info lifecycle XSSTRON@1.0.0~start: XSSTRON@1.0.0
7 verbose lifecycle XSSTRON@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle XSSTRON@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/soufiane/Tools/XSS/XSSTRON/node_modules/.bin:/home/soufiane/.local/bin:/home/soufiane/.rvm/gems/ruby-3.0.0/bin:/home/soufiane/.rvm/gems/ruby-3.0.0@global/bin:/usr/share/rvm/rubies/ruby-3.0.0/bin:/home/soufiane/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/share/rvm/bin
9 verbose lifecycle XSSTRON@1.0.0~start: CWD: /home/soufiane/Tools/XSS/XSSTRON
10 silly lifecycle XSSTRON@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle XSSTRON@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle XSSTRON@1.0.0~start: Failed to exec start script
13 verbose stack Error: XSSTRON@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid XSSTRON@1.0.0
15 verbose cwd /home/soufiane/Tools/XSS/XSSTRON
16 verbose Linux 5.4.0-60-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error XSSTRON@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the XSSTRON@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by soufianetahiri** [comment]
Fixed it by:

npm cache clean --force
rm -rf node_modules package-lock.json

And reinstall.
